#ifndef SRC_TENDISPLUS_COMMANDS_RELEASE_H_
#define SRC_TENDISPLUS_COMMANDS_RELEASE_H_

#define TENDISPLUS_GIT_SHA1 "3bd72973"
#define TENDISPLUS_GIT_DIRTY "17"
#define TENDISPLUS_BUILD_ID "VM_33_225_centos-1592465018"

#include <stdint.h>
uint64_t redisBuildId(void);

#endif  // SRC_TENDISPLUS_COMMANDS_RELEASE_H_
