name: Compile
description: Compile C++ code and perform basic setup

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Set Up TCL
      shell: bash
      run: sudo apt-get install tcl8.6
    - name: Init Submodules
      shell: bash
      run: |
        git submodule update --init --recursive
    - name: Build
      shell: bash
      run: |
        mkdir build && cd build
        git config --global user.email "you@example.com"
        git config --global user.name "yourname"
        cmake -DTENDIS_DEBUG=ON ..
        cmake --build . -j20
